// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_PROJECT_ID = "zkktyrxdkugkdhaiqxkv";
export const SUPABASE_URL = "https://zkktyrxdkugkdhaiqxkv.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpra3R5cnhka3Vna2RoYWlxeGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyNTIzMDIsImV4cCI6MjA5MDgyODMwMn0.UDjCeJqHIAB6Fp7bUmmk3svLF7xxZek61oy3N-JMvSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});